if has("multi_byte")
  set encoding=utf-8
  setglobal fileencoding=utf-8
else
  echoerr "Sorry, this version of (g)vim was not compiled with +multi_byte"
endif

" enable syntax highlighting
syntax on
colorscheme fancy

" Display line numbers on the left
set number

" Enable use of the mouse for all modes
set mouse=a

" Allow backspapcing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" Enable autoindent
set autoindent
set smartindent

" Spaces are used
set shiftwidth=4
set tabstop=4

" I want to find what I'm looking for
set hlsearch

" Chromebook yank support
let g:os = substitute(system('uname -n'), '\n', '', '')
if g:os == "penguin"
	source ~/dotfiles/vim/after/plugin/osc52.vim
	vmap <C-c> y:call SendViaOSC52(getreg('"'))<cr>
endif

" WSL yank support
let s:clip = "/mnt/c/Windows/System32/clip.exe"
if executable(s:clip)
	augroup WSLYank
    	autocmd!
    	autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
	augroup END
endif

" Compiler
compiler gcc

" Remove trailing whitespace
au BufWritePre * "%s/\s\+$//e"
