if has("multi_byte")
  set encoding=utf-8
  setglobal fileencoding=utf-8
else
  echoerr "Sorry, this version of (g)vim was not compiled with +multi_byte"
endif

" Enable syntax highlighting
syntax on
colorscheme fancy
if exists('+termguicolors')
	set termguicolors
else
	set t_Co=256
endif

" Compiler
compiler gcc

" Display line numbers on the left
set number

" Enable use of the mouse for all modes
set mouse=a

" Allow backspapcing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" Enable autoindent
set autoindent
set smartindent
set pastetoggle=<F3>

" Spaces are used
set expandtab
set shiftwidth=2
set tabstop=2

" I want to find what I'm looking for
set hlsearch

" Highlight the matching bracket
set showmatch

" Auto-insert closing brackets
inoremap "<Tab>	""<left>
inoremap '<Tab>	''<left>
inoremap (<Tab>	()<left>
inoremap <<Tab>	<><left>
inoremap [<Tab>	[]<left>
inoremap {<Tab>	{}<left>
inoremap {;		{<CR>};<ESC>O

" Change .viminfo location
set viminfo+=n~/.vim/viminfo

" Remove trailing whitespace
au BufWritePre * "%s/\s\+$//e"

" ChromeOS yank support
let g:os = substitute(system('uname -n'), '\n', '', '')
if g:os == "penguin"
	augroup osc52
		autocmd!
		autocmd TextYankPost * if v:event.operator ==# 'y' | call SendViaOSC52(getreg(v:event.regname)) | endif
	augroup END
endif

" WSL yank support
let s:clip = "/mnt/c/Windows/System32/clip.exe"
if executable(s:clip)
	augroup WSLYank
		autocmd!
		autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
	augroup END
endif

" No history or bookmarks
let g:netrw_dirhistmax = 0
